# Capítulo 5 Arreglos

## Problemas para manejo de vectores


### 1. Escriba un algoritmo que cargue un vector de 5 elementos; luego sume todos los elementos del vector. Imprima al vector y la suma.


In [1]:
lista = [7,8,9,4,3]
suma = sum(lista)

print(lista) 
print(suma)

[7, 8, 9, 4, 3]
31


### 2. Dado un conjunto de 50 números enteros, desarrolle los siguientes procesos:
#### Cargue en el vector los datos de entrada.
#### • Obtenga una sumatoria de todos los números pares almacenados en las posiciones pares del vector.
#### • Obtener una sumatoria de todos los números impares almacenados en el vector.
#### • Imprimir el vector, ambas sumatorias y un mensaje que defina si las sumatorias son iguales o no.

In [1]:
vector = []
n_enteros = 0
suma_pares = 0
suma_impares = 0

for i in range(1,51):
    vector.append(int(input("Escribe un número: ")))
    
for i in vector:
    if i % 2 ==0:
        suma_pares+=i
    else:
        suma_impares+=i

print(vector)
print(suma_pares)
print(suma_impares)
        
if suma_pares == suma_impares:
    print("Son iguales")
else:
    print("No son iguales")

Escribe un número: 1
Escribe un número: 2
Escribe un número: 3
Escribe un número: 4
Escribe un número: 5
Escribe un número: 6
Escribe un número: 7
Escribe un número: 8
Escribe un número: 9
Escribe un número: 10
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
30
25
No son iguales


### 3. Una clase de 35 estudiantes hace un examen; sus calificaciones se almacenan en un vector R. Elabore un algoritmo que encuentre la cantidad de estudiantes con notas perfectas, es decir, calificaciones de 100. Imprima el resultado.

In [21]:
R = {'Alexander':70,'Kirán': 100,"Ariel":90,'Priscilla':15,"Fernando Salazar":85,"Alejandro":100,'Fernando Cutire':100,'William':99,
    'Joshua':60,'Johan':80,'Esperanza':50,'Génesis':60,'Luis':80,'David':100,'Jonathan':50,'Jordan':30,'Agustin':88,'Adilem':98,
    'Cesar':60,'Daniela':90,'Vicente':59,'Jack':40,'Mara':70,'Melly':56,'Paul':90,'Michael':100,'Paola':15,'Rafael':100,
    'Asley':80,'Xochil':40,'Julio':90,'Isaías':10,'Eduardo Carrera':100,'Mathews':10,'Allison':15}
notas_perfectas = []


print("Número de estudiantes: ",len(R))

for i in R:
    if R[i] == 100:
        notas_perfectas.append(i)
        
print("Cantidad de estudiantes con notas perfectas: ",len(notas_perfectas))
print("Los estudiantes son: ", notas_perfectas)

Número de estudiantes:  35
Cantidad de estudiantes con notas perfectas:  7
Los estudiantes son:  ['Kirán', 'Alejandro', 'Fernando Cutire', 'David', 'Michael', 'Rafael', 'Eduardo Carrera']


### 4. A partir del planteamiento del problema 3, calcule el promedio de las notas y el número de estudiantes con notas menores que 60. Imprima los resultados.

In [36]:
promedio = 0
notas_menores_60 = []

for i in R:
    promedio+=R[i]
    if R[i] < 60:
        notas_menores_60.append(i)
    
promedio = promedio /35

print(promedio)
print(len(notas_menores_60))

68.0
12


### 5. Se tienen las calificaciones de 50 estudiantes. Elabore un algoritmo que calcule el promedio de las calificaciones e imprima todas aquellas notas que sean superiores al promedio. 

In [6]:
R = {'Alexander':70,'Kirán': 100,"Ariel":90,'Priscilla':15,"Fernando Salazar":85,"Alejandro":100,'Fernando Cutire':100,'William':99,
    'Joshua':60,'Johan':80,'Esperanza':50,'Génesis':60,'Luis':80,'David':100,'Jonathan':50,'Jordan':30,'Agustin':88,'Adilem':98,
    'Cesar':60,'Daniela':90,'Vicente':59,'Jack':40,'Mara':70,'Melly':56,'Paul':90,'Michael':100,'Paola':15,'Rafael':100,
    'Asley':80,'Xochil':40,'Julio':90,'Isaías':10,'Eduardo Carrera':100,'Mathews':10,'Allison':15,'Klemelys':60,'Pablo':60,
    'Cianky':50,'Andrés':60,'Karen':10,'Isabella':30,'Verónica':10,'Mateo':30,'José':10,'Joyner':30,'Juan':80,'Micol':100,
    'Mariangela':80,'Orlando':20,'Ulises':100}
notas_superiores = []

promedio = 0

for i in R:
    promedio+=R[i]
promedio = promedio / len(R)
for n in R:
    if R[n] > 60:
        notas_superiores.append(R[n])
    

print("Valor promedio: ", promedio)
print("Notas mayores al promedio: ",notas_superiores)

Valor promedio:  62.2
Notas mayores al promedio:  [70, 100, 90, 85, 100, 100, 99, 80, 80, 100, 88, 98, 90, 70, 90, 100, 100, 80, 90, 100, 80, 100, 80, 100]


### 6. Diseñe un algoritmo que lea un conjunto de 50 datos de entrada y cargue una tabla de 100 elementos de manera que cada valor leído quede en la posición par del vector. 

In [12]:
vector = []

for i in range(1,51):
    vector.append(" ")
    vector.append((input("Introduce una entrada: ")))

print(vector)

Introduce una entrada: 1
Introduce una entrada: 2
Introduce una entrada: 3
Introduce una entrada: 4
Introduce una entrada: 5
Introduce una entrada: 6
Introduce una entrada: 7
Introduce una entrada: 8
Introduce una entrada: 9
Introduce una entrada: 10
Introduce una entrada: 11
Introduce una entrada: 12
Introduce una entrada: 13
Introduce una entrada: 14
Introduce una entrada: 15
Introduce una entrada: 16
Introduce una entrada: 17
Introduce una entrada: 18
Introduce una entrada: 19
Introduce una entrada: 20
Introduce una entrada: 21
Introduce una entrada: 22
Introduce una entrada: 23
Introduce una entrada: 2
Introduce una entrada: 4
Introduce una entrada: 5
Introduce una entrada: 6
Introduce una entrada: 1
Introduce una entrada: f
Introduce una entrada: er
Introduce una entrada: g
Introduce una entrada: d
Introduce una entrada: v
Introduce una entrada: e
Introduce una entrada: t
Introduce una entrada: e
Introduce una entrada: a
Introduce una entrada: l
Introduce una entrada: a
Introduce 

In [59]:
vector = []

for i in range(1,21):
    vector.append(float(input("Introduzca estaturas: ")))
    
a = max(vector)
index = vector.index(a)

print("La estatura del más alto es: " a)
print("La posición en que se encuentra es:"index)

Introduzca estaturas: 1.40
Introduzca estaturas: 1.50
Introduzca estaturas: 1.80
Introduzca estaturas: 1.40
Introduzca estaturas: 1.30
Introduzca estaturas: 1.10
Introduzca estaturas: 1.20
Introduzca estaturas: 1.30
Introduzca estaturas: 1.40
Introduzca estaturas: 1.50
Introduzca estaturas: 1.60
Introduzca estaturas: 1.70
Introduzca estaturas: 1.80
Introduzca estaturas: 1.90
Introduzca estaturas: 1.10
Introduzca estaturas: 1.20
Introduzca estaturas: 1.30
Introduzca estaturas: 1.40
Introduzca estaturas: 1.45
Introduzca estaturas: 1.95
1.95
19


### 8. Elabore un algoritmo que cargue un vector de 5 elementos y determine la suma y el producto de todos los elementos del vector. Imprima la suma y el producto.

In [68]:
vector = []
suma = 0
producto = 1

for i in range(1,6):
    vector.append(int(input("Introduce los números: ")))
for n in vector:
    suma+=n
    producto*=n

print(suma)
print(producto)


Introduce los números: 1
Introduce los números: 2
Introduce los números: 3
Introduce los números: 4
Introduce los números: 5
15
120


### 9. Cree un algoritmo que considere un vector de 100 elementos y luego lea un conjunto de 51 valores y los almacene en el vector. A continuación, debe leerse un valor numérico e investigar el número de veces que el valor leído aparece en el vector. Imprima el valor leído y el número de veces que se repite en el vector.

In [16]:
lectura = []
suma = 0

for i in range(1,51):
    lectura.append(int(input("Introduce tu elemento: ")))

a = int(input("Introduce un valor numérico: "))


for n in lectura:
    if n==a:
        suma+=1
    
print(lectura)        
print("Tu valor numérico fue: ", a)
print("El número de veces que apareció fue: ", suma)

Introduce tu elemento: 1
Introduce tu elemento: 2
Introduce tu elemento: 3
Introduce tu elemento: 4
Introduce tu elemento: 5
Introduce tu elemento: 6
Introduce tu elemento: 7
Introduce tu elemento: 9
Introduce tu elemento: 10
Introduce tu elemento: 11
Introduce tu elemento: 1
Introduce tu elemento: 2
Introduce tu elemento: 3
Introduce tu elemento: 45
Introduce tu elemento: 67
Introduce tu elemento: 42
Introduce tu elemento: 21
Introduce tu elemento: 34
Introduce tu elemento: 6
Introduce tu elemento: 88
Introduce tu elemento: 12
Introduce tu elemento: 56
Introduce tu elemento: 712
Introduce tu elemento: 121
Introduce tu elemento: 434
Introduce tu elemento: 09
Introduce tu elemento: 12
Introduce tu elemento: 45
Introduce tu elemento: 21
Introduce tu elemento: 535
Introduce tu elemento: 132
Introduce tu elemento: 43
Introduce tu elemento: 1
Introduce tu elemento: 1
Introduce tu elemento: 1
Introduce tu elemento: 2
Introduce tu elemento: 3
Introduce tu elemento: 4
Introduce tu elemento: 5


### 10. Sean nombre y sexo dos vectores que contienen el nombre y el sexo de cada uno de los miembros de un club juvenil de 25 miembros cada uno. Exprese Masculino y Femenino mediante (‘m’, ‘f’), respectivamente. Escriba un algoritmo que pueda generar dos nuevos vectores, llamados ma y fe, de tal forma que ma contenga el nombre de todos los hombres en orden alfabético y fe contenga el nombre de todas las mujeres en el mismo orden.

In [48]:
#La CUTI SOLUCIÓN
nombres_sexo = {'Fernando':'m','Enrique':'m','Alejandro':'m','Luis':'m','Esteban':'m','Jonathan':'m',
                'Rafael':'m','Orlando':'m','William':'m','Rubén':'m','Admin':'m',
         'Asley':'m','Jorge':'m','Daniel':'m','Cracklitos':'m','Francisco':'m','Yader':'m','Abdiel':'m',
        'Eduardo':'m','José':'m','Christian':'m','Ulises':'m','Krysnar':'m',
         'Castro':'m','Diego':'m','Esperanza':'f','Adilem':'f','Priscilla':'f','María':'f','Daniela':'f',
        'Ariel':'f','Eloisa':'f','Yexely':'f','Xochil':'f','Klemelys':'f','Paola':'f',
        'Paula':'f','Melly':'f','Mara':'f','Britanny':'f','Victoria':'f','Sofía':'f','Karen':'f',
        'Isabella':'f','Mariangela':'f','Verónica':'f','Lorena':'f','Celeste':'f','Andrea':'f','Vlieg':'f'}

ma = []
fe = []

for i in nombres_sexo:
        if nombres_sexo[i] == 'm':
            ma.append(i)
        else:
            fe.append(i)
        
print("Lista de hombres ordenados alfabéticamente")
print("-------------------------------------------------------------------------------------------------------------------------------")
print(sorted(ma))
print()
print("Lista de mujeres ordenadas alfabéticamente")
print("-------------------------------------------------------------------------------------------------------------------------------")
print(sorted(fe))

Lista de hombres ordenados alfabéticamente
-------------------------------------------------------------------------------------------------------------------------------
['Abdiel', 'Admin', 'Alejandro', 'Asley', 'Castro', 'Christian', 'Cracklitos', 'Daniel', 'Diego', 'Eduardo', 'Enrique', 'Esteban', 'Fernando', 'Francisco', 'Jonathan', 'Jorge', 'José', 'Krysnar', 'Luis', 'Orlando', 'Rafael', 'Rubén', 'Ulises', 'William', 'Yader']

Lista de mujeres ordenadas alfabéticamente
-------------------------------------------------------------------------------------------------------------------------------
['Adilem', 'Andrea', 'Ariel', 'Britanny', 'Celeste', 'Daniela', 'Eloisa', 'Esperanza', 'Isabella', 'Karen', 'Klemelys', 'Lorena', 'Mara', 'Mariangela', 'María', 'Melly', 'Paola', 'Paula', 'Priscilla', 'Sofía', 'Verónica', 'Victoria', 'Vlieg', 'Xochil', 'Yexely']


In [80]:
#La solución de ALEJO
class Vector:
    def __init__(self):
        global genero
        global nombre
        global vector
        genero = []
        nombre = []
        vector = [genero, nombre]

    def add(self, g, n):
        vector[0].append(g)
        vector[1].append(n)

    def read(self):
        #print(range(len(vector)))
        for c in range(len(vector[0])):
            print(vector[0][c-1] + " " + vector[1][c-1])


v = Vector()

v.add("f", "b")
v.add("m", "Alejandro")
v.add("k", "c")
v.add("f","Mujer")
v.add("C","Hey")
v.read()

C Hey
f b
m Alejandro
k c
f Mujer


## Problemas para manejo de matrices


In [38]:
>>> import numpy as np

### 1. Escriba un algoritmo que lea una matriz de 36 elementos por columnas y visualice las mismas por filas. A continuación encuentre los elementos mayor y menor y sus posiciones.

In [79]:
arreglo = np.arange(36).reshape(6,6)
print(array)


# Encontrar el valor máximo de todo el arreglo
v_max = numpy.amax(arreglo)
print("\n El valor máximo encontrado es: ", v_max)

#Obtener el índice del valor máximo del arreglo
indice_max = numpy.where(arreglo == numpy.amax(arreglo))
print('Lista de las coordenadas del valor máximo del arreglo : ')

# zip the 2 arrays to get the exact coordinates
lista_coordenadas_max = list(zip(indice_max[0], indice_max[1]))

# travese over the list of cordinates
for coordenada in lista_coordenadas_max:
    print(coordenada)
    

#Encontrar el valor mínimo de todo el arreglo
v_min = numpy.amin(arreglo)
print("\n El valor mínimo encontrado es: ", v_min)

#Obtener el índice del valor mínimo del arreglo
indice_min = numpy.where(arreglo == v_min)
print('Lista de las coordenadas del valor mínimo del arreglo : ')

# zip the 2 arrays to get the exact coordinates
lista_coordenadas_min = list(zip(indice_min[0], indice_min[1]))

# travese over the list of cordinates
for coordenada in lista_coordenadas_min:
    print(coordenada)



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

 El valor máximo encontrado es:  35
Lista de las coordenadas del valor máximo del arreglo : 
(5, 5)

 El valor mínimo encontrado es:  0
Lista de las coordenadas del valor mínimo del arreglo : 
(0, 0)


### 2. Cargue una matriz 4*4 con números, luego sume los elementos de cada fila y guárdelos en un vector fila; luego sume todos los elementos de cada columna y guárdelos en un vector columna.

In [86]:
>>> import numpy as np
>>> a = np.arange(12).reshape(4,3)
print(a)
>>> a.sum(axis=1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([ 3, 12, 21, 30])

In [99]:
a = np.random.rand(4,4)
print(a)

fila = a.sum(axis=1)
columna = a.sum(axis=0)

print("\nLa suma de todos los elementos de las filas es", fila)
print("\nLa suma de todos los elementos de las columnas es", columna)

[[0.58858327 0.50007339 0.58003528 0.00288118]
 [0.51407696 0.68536508 0.27661777 0.14263711]
 [0.30033619 0.28201455 0.38280305 0.02981355]
 [0.72902365 0.38470521 0.20849844 0.99657001]]

La suma de todos los elementos de las filas es [1.67157312 1.61869692 0.99496734 2.31879732]

La suma de todos los elementos de las columnas es [2.13202008 1.85215823 1.44795454 1.17190185]


### 3. Cargue dos matrices cuadradas y realice las siguientes operaciones: SUMA, RESTA. Deberá imprimir cada matriz al lado de la otra.

In [125]:
a = np.random.randint(5, size=(2, 2))
b = np.random.randint(5, size=(2, 2))

print("\n",a)
print("\n",b)

print("\nLa suma es: ")
print("\n", a + b)
print("\nLa resta es: ")
print("\n", a - b)



 [[3 2]
 [0 0]]

 [[3 0]
 [2 1]]

La suma es: 

 [[6 2]
 [2 1]]

La resta es: 

 [[ 0  2]
 [-2 -1]]


### 4. Una agencia de ventas de vehículos distribuye 15 modelos diferentes y tiene en su planilla a 10 vendedores. Elabore un algoritmo que muestre la siguiente información:
#### • Un informe mensual de las ventas por vendedor y modelo.
#### • Un informe mensual del total de autos vendidos por vendedor y modelo.
#### • Y por último se desea entregar un premio al mejor vendedor, para ello considere como criterio de selección el que más autos vendió.

## Estoy teniendo problemas en:
### No puedo tener 15 modelos de carros y anexarlos a 10 vendedores porque me sale error
### No puedo acceder al vendedor con mayor ventas e imprimir su nombre

In [39]:
import pandas as pd

In [59]:
# Listas
vehiculos1 = ['Toyota Corolla', 'Ford F-Series', 'Volkswagen Golf', 'Volkswagen Beetle', 'Ford Escort', 
            'Fiat 124', 'Honda Civic', 'Ford Model T', 'Volkswagen Passat', 'Chevrolet Impala', 'Nissan Qhasquai',
            'Tesla Model S', 'Chery QQ', 'Kia Picanto', 'Ferrari Lamborghini']

vehiculos = ['Toyota Corolla', 'Ford F-Series', 'Volkswagen Golf', 'Volkswagen Beetle', 'Ford Escort', 
            'Fiat 124', 'Honda Civic', 'Ford Model T', 'Volkswagen Passat', 'Chevrolet Impala']

vendedores = ['Carlos','Esperanza','Ariel','Fernando','Juan','Jhon','Jordan','Joyner','Benito','René']

ventas = [1200000, 1300000, 160000, 180000, 20000, 400000, 80000, 45000, 100000, 120000]

numero_de_autos_vendidos = [10,20,40,60,8,15,20,7,9,10]

zippedList1 =  list(zip(vendedores, vehiculos,ventas))
zippedList2 =  list(zip(vendedores, vehiculos, numero_de_autos_vendidos))


#Dataframes

informe_1 = pd.DataFrame(zippedList1, columns = ['Vendedores','Modelos','Ventas'], 
                         index = ['a','b','c','d','e','f','g','h','i','j'])

informe_2 = pd.DataFrame(zippedList2, columns = ['Vendedores' , 'Vehículos', 'Número de autos vendidos'], 
                     index=['a','b','c','d','e','f','g','h','i','j']) 

#Hallar el máximo valor del arreglo

informe_2['Número de autos vendidos'].max()

#Print
print(informe_1)
print("\n",informe_2)
print("\n",informe_2.loc[informe_2['Número de autos vendidos'].idxmax()])


  Vendedores            Modelos   Ventas
a     Carlos     Toyota Corolla  1200000
b  Esperanza      Ford F-Series  1300000
c      Ariel    Volkswagen Golf   160000
d   Fernando  Volkswagen Beetle   180000
e       Juan        Ford Escort    20000
f       Jhon           Fiat 124   400000
g     Jordan        Honda Civic    80000
h     Joyner       Ford Model T    45000
i     Benito  Volkswagen Passat   100000
j       René   Chevrolet Impala   120000

   Vendedores          Vehículos  Número de autos vendidos
a     Carlos     Toyota Corolla                        10
b  Esperanza      Ford F-Series                        20
c      Ariel    Volkswagen Golf                        40
d   Fernando  Volkswagen Beetle                        60
e       Juan        Ford Escort                         8
f       Jhon           Fiat 124                        15
g     Jordan        Honda Civic                        20
h     Joyner       Ford Model T                         7
i     Benito  Volkswagen 

### 5. Industria Moderna S. A. le encarga diseñar un algoritmo que refleje las ventas por departamento (totales por departamento); para ello se cuenta con los siguientes datos de entrada: código de departamento, nombre del departamento, código de artículo, monto de la venta. El almacén cuenta con 5 departamentos y cada departamento con 10 artículos.
Salida deseada:
INDUSTRIAS MODERNAS S.A.
VENTAS POR DEPARTAMENTO
DEPARTAMENTO: x - - - - - - - -x
COD. DE ARTÍCULO MONTO DE LA VENTA
99 999.99
TOTAL DEL DEPARTAMENTO: 9999.99

In [14]:
import numpy as np
import pandas as pd

In [41]:
class Depto:
    def __init__(self, cod_dpto, nombre_dpto,cod_arts=None,mon_ventas=None,t_ventas=0):
        self.cod_dpto = cod_dpto
        self.nombre_dpto = nombre_dpto
        self.cod_arts = []
        self.mon_ventas = []
        self.t_ventas = t_ventas
    
    #Crea un departamento
    def crear_Depto(self):
        print("El departamento {} ha sido creado".format(self.nombre_dpto))
    
    def agregar_articulo(self, cod_articulo, m_venta):
        #print("\nSe esta creando un articulo")
        #print("\n\tSe creo el articulo codigo {} y monto de venta {} ".format(cod_articulo, m_venta))
        self.cod_arts.append(cod_articulo)
        self.mon_ventas.append(m_venta)
    
    def imprimir_lista(self):
        print(self.cod_arts)
        print(self.mon_ventas)
    
    def crear_data_frame(self):
        lista_zippeada = list(zip(self.cod_arts,self.mon_ventas))
        #Creando un dataframe desde una lista
        departamento = pd.DataFrame(lista_zippeada, columns = ['COD DE ARTÍCULO','MONTO DE LA VENTA',], 
                                    index=['1','2','3','4','5','6','7','8','9','10'])
        print("\nDEPARTAMENTO {}, {} \n".format(self.cod_dpto, self.nombre_dpto))
        print(departamento)
        self.t_ventas = departamento['MONTO DE LA VENTA'].sum()
    
    def total_departamento(self):
        print("TOTAL DEL DEPARTAMENTO: ",self.t_ventas)



In [42]:
ventas = Depto(125, 'Ventas')
ventas.agregar_articulo(89, 125)
ventas.agregar_articulo(45, 15)
ventas.agregar_articulo(25, 55)
ventas.agregar_articulo(45, 16)
ventas.agregar_articulo(24,900)
ventas.agregar_articulo(25,9000)
ventas.agregar_articulo(26,1200)
ventas.agregar_articulo(27,7000)
ventas.agregar_articulo(28,8000)
ventas.agregar_articulo(29,9500)

marketing = Depto(67,'Marketing')
marketing.agregar_articulo(10,400)
marketing.agregar_articulo(11,100)
marketing.agregar_articulo(12,200)
marketing.agregar_articulo(13,300)
marketing.agregar_articulo(14,90)
marketing.agregar_articulo(15,90)
marketing.agregar_articulo(16,120)
marketing.agregar_articulo(17,700)
marketing.agregar_articulo(18,800)
marketing.agregar_articulo(19,950)

innovacion = Depto(70,'Innovación')
innovacion.agregar_articulo(30,250)
innovacion.agregar_articulo(31,540)
innovacion.agregar_articulo(32,230)
innovacion.agregar_articulo(33,980)
innovacion.agregar_articulo(34,10)
innovacion.agregar_articulo(35,100)
innovacion.agregar_articulo(36,200)
innovacion.agregar_articulo(37,750)
innovacion.agregar_articulo(38,400)
innovacion.agregar_articulo(39,950)

software = Depto(71,'Software')
software.agregar_articulo(40,40)
software.agregar_articulo(41,50)
software.agregar_articulo(42,60)
software.agregar_articulo(43,380)
software.agregar_articulo(44,230)
software.agregar_articulo(45,450)
software.agregar_articulo(46,50)
software.agregar_articulo(47,90)
software.agregar_articulo(48,80)
software.agregar_articulo(49,90)

gerencia = Depto(72,'Gerencia')
gerencia.agregar_articulo(50,400)
gerencia.agregar_articulo(51,100)
gerencia.agregar_articulo(52,200)
gerencia.agregar_articulo(53,30)
gerencia.agregar_articulo(54,90)
gerencia.agregar_articulo(55,40)
gerencia.agregar_articulo(56,120)
gerencia.agregar_articulo(57,710)
gerencia.agregar_articulo(58,820)
gerencia.agregar_articulo(59,95)

        
print("INDUSTRIAS MODERNAS SA")
print("VENTAS POR DEPARTAMENTO")
ventas.crear_data_frame()
ventas.total_departamento()
marketing.crear_data_frame()
marketing.total_departamento()
innovacion.crear_data_frame()
innovacion.total_departamento()
software.crear_data_frame()
software.total_departamento()
gerencia.crear_data_frame()
gerencia.total_departamento()



INDUSTRIAS MODERNAS SA
VENTAS POR DEPARTAMENTO

DEPARTAMENTO 125, Ventas 

    COD DE ARTÍCULO  MONTO DE LA VENTA
1                89                125
2                45                 15
3                25                 55
4                45                 16
5                24                900
6                25               9000
7                26               1200
8                27               7000
9                28               8000
10               29               9500
TOTAL DEL DEPARTAMENTO:  35811

DEPARTAMENTO 67, Marketing 

    COD DE ARTÍCULO  MONTO DE LA VENTA
1                10                400
2                11                100
3                12                200
4                13                300
5                14                 90
6                15                 90
7                16                120
8                17                700
9                18                800
10               19                950
TOTAL 

### 6. Con base en el anterior planteamiento, elabore un algoritmo que realice los siguientes procesos:
#### • Determinar el departamento de mayor venta.
#### • Calcular el promedio de ventas por departamento.
#### • Determinar el artículo de mayor venta en el almacén

In [90]:
class Depto:
    def __init__(self, cod_dpto, nombre_dpto,cod_arts=None,mon_ventas=None,t_ventas=0,n_ventas=None, promedio_ventas=0,
                mayor_venta=0):
        self.cod_dpto = cod_dpto
        self.nombre_dpto = nombre_dpto
        self.cod_arts = []
        self.mon_ventas = []
        self.t_ventas = t_ventas
        self.n_ventas = []
        self.promedio_ventas = promedio_ventas
        self.mayor_venta = mayor_venta 
        
    #Crea un departamento
    def crear_Depto(self):
        print("El departamento {} ha sido creado".format(self.nombre_dpto))
    
    def agregar_articulo(self, cod_articulo, m_venta, n_venta):
        #print("\nSe esta creando un articulo")
        #print("\n\tSe creo el articulo codigo {} y monto de venta {} ".format(cod_articulo, m_venta))
        self.cod_arts.append(cod_articulo)
        self.mon_ventas.append(m_venta)
        self.n_ventas.append(n_venta)
    
    def imprimir_lista(self):
        print(self.cod_arts)
        print(self.mon_ventas)
    
    def crear_data_frame(self):
        lista_zippeada = list(zip(self.cod_arts,self.mon_ventas,self.n_ventas))
        #Creando un dataframe desde una lista
        departamento = pd.DataFrame(lista_zippeada, columns = ['COD DE ARTÍCULO','MONTO DE LA VENTA','VENTAS'], 
                                    index=['1','2','3','4','5','6','7','8','9','10'])
        print("\nDEPARTAMENTO {}, {} \n".format(self.cod_dpto, self.nombre_dpto))
        print(departamento)
        self.t_ventas = departamento['MONTO DE LA VENTA'].sum()
        self.n_ventas = departamento['VENTAS'].sum()
        self.promedio_ventas = departamento['VENTAS'].mean() 
        self.mayor_venta = departamento.nlargest(1,['VENTAS']) 
    
    def total_monto(self):
        print("TOTAL DEL DEPARTAMENTO: ",self.t_ventas)
    
    def total_ventas(self):
        return self.n_ventas
    
    def depto_nombre(self):
        return self.nombre_dpto
    
    def promedio_ventas(self):
        return self.promedio_ventas
    
    def mayor_venta(self):
        return self.mayor_venta

In [91]:
ventas = Depto(125, 'Ventas')
ventas.agregar_articulo(89, 125,24)
ventas.agregar_articulo(45, 15,31)
ventas.agregar_articulo(25, 55,45)
ventas.agregar_articulo(45, 16,12)
ventas.agregar_articulo(24,900,23)
ventas.agregar_articulo(25,9000,45)
ventas.agregar_articulo(26,1200,32)
ventas.agregar_articulo(27,7000,12)
ventas.agregar_articulo(28,8000,78)
ventas.agregar_articulo(29,9500,90)

marketing = Depto(67,'Marketing')
marketing.agregar_articulo(10,400,45)
marketing.agregar_articulo(11,100,23)
marketing.agregar_articulo(12,200,46)
marketing.agregar_articulo(13,300,12)
marketing.agregar_articulo(14,90,17)
marketing.agregar_articulo(15,90,23)
marketing.agregar_articulo(16,120,14)
marketing.agregar_articulo(17,700,16)
marketing.agregar_articulo(18,800,18)
marketing.agregar_articulo(19,950,24)

innovacion = Depto(70,'Innovación')
innovacion.agregar_articulo(30,250,34)
innovacion.agregar_articulo(31,540,12)
innovacion.agregar_articulo(32,230,65)
innovacion.agregar_articulo(33,980,90)
innovacion.agregar_articulo(34,10,1)
innovacion.agregar_articulo(35,100,2)
innovacion.agregar_articulo(36,200,56)
innovacion.agregar_articulo(37,750,43)
innovacion.agregar_articulo(38,400,108)
innovacion.agregar_articulo(39,950,47)

software = Depto(71,'Software')
software.agregar_articulo(40, 40, 43)
software.agregar_articulo(41, 50, 12)
software.agregar_articulo(42, 60, 45)
software.agregar_articulo(43,380, 32)
software.agregar_articulo(44,230, 24)
software.agregar_articulo(45,450, 45)
software.agregar_articulo(46,50, 56)
software.agregar_articulo(47,90, 41)
software.agregar_articulo(48,80, 12)
software.agregar_articulo(49,90, 13)

gerencia = Depto(72,'Gerencia')
gerencia.agregar_articulo(50,400, 98)
gerencia.agregar_articulo(51,100, 67)
gerencia.agregar_articulo(52,200, 45)
gerencia.agregar_articulo(53,30, 56)
gerencia.agregar_articulo(54,90, 78)
gerencia.agregar_articulo(55,40, 45)
gerencia.agregar_articulo(56,120, 34)
gerencia.agregar_articulo(57,710, 45)
gerencia.agregar_articulo(58,820, 90)
gerencia.agregar_articulo(59,95, 21)

        
print("INDUSTRIAS MODERNAS SA")
print("VENTAS POR DEPARTAMENTO")
ventas.crear_data_frame()
ventas.total_monto()
marketing.crear_data_frame()
marketing.total_monto()
innovacion.crear_data_frame()
innovacion.total_monto()
software.crear_data_frame()
software.total_monto()
gerencia.crear_data_frame()
gerencia.total_monto()


INDUSTRIAS MODERNAS SA
VENTAS POR DEPARTAMENTO

DEPARTAMENTO 125, Ventas 

    COD DE ARTÍCULO  MONTO DE LA VENTA  VENTAS
1                89                125      24
2                45                 15      31
3                25                 55      45
4                45                 16      12
5                24                900      23
6                25               9000      45
7                26               1200      32
8                27               7000      12
9                28               8000      78
10               29               9500      90
TOTAL DEL DEPARTAMENTO:  35811

DEPARTAMENTO 67, Marketing 

    COD DE ARTÍCULO  MONTO DE LA VENTA  VENTAS
1                10                400      45
2                11                100      23
3                12                200      46
4                13                300      12
5                14                 90      17
6                15                 90      23
7                1

In [122]:
# Determinar el departamento de mayor ventas
deptos = [ventas.depto_nombre(), innovacion.depto_nombre(), marketing.depto_nombre(), gerencia.depto_nombre(), 
          software.depto_nombre()]
ventas_deptos = [ventas.total_ventas(), innovacion.total_ventas(),marketing.total_ventas(),gerencia.total_ventas()
                ,software.total_ventas()]

diccionario = dict(zip(deptos, ventas_deptos))

maximo = max(diccionario, key=diccionario.get)
print("DEPARTAMENTO DE MAYOR VENTAS")
print(maximo, diccionario[maximo])


# Calcular el promedio de ventas por departamento
print("\nPROMEDIO DE VENTAS\n")
print('DEPARTAMENTO {} PROMEDIO DE VENTAS {}'.format(ventas.depto_nombre(), ventas.promedio_ventas))
print('DEPARTAMENTO {} PROMEDIO DE VENTAS {}'.format(innovacion.depto_nombre(), innovacion.promedio_ventas))
print('DEPARTAMENTO {} PROMEDIO DE VENTAS {}'.format(marketing.depto_nombre(), marketing.promedio_ventas))
print('DEPARTAMENTO {} PROMEDIO DE VENTAS {}'.format(gerencia.depto_nombre(), gerencia.promedio_ventas))
print('DEPARTAMENTO {} PROMEDIO DE VENTAS {}'.format(software.depto_nombre(), software.promedio_ventas))


# Determinar el articulo de mayor venta en el almacen
print('\nARTICULO DE MAYOR VENTA EN EL ALMACEN\n')
mayor_venta = []

mayor_venta.append(innovacion.mayor_venta)
mayor_venta.append(ventas.mayor_venta)
mayor_venta.append(marketing.mayor_venta)
mayor_venta.append(gerencia.mayor_venta)
mayor_venta.append(software.mayor_venta)

print(mayor_venta[0])


DEPARTAMENTO DE MAYOR VENTAS
Gerencia 579

PROMEDIO DE VENTAS

DEPARTAMENTO Ventas PROMEDIO DE VENTAS 39.2
DEPARTAMENTO Innovación PROMEDIO DE VENTAS 45.8
DEPARTAMENTO Marketing PROMEDIO DE VENTAS 23.8
DEPARTAMENTO Gerencia PROMEDIO DE VENTAS 57.9
DEPARTAMENTO Software PROMEDIO DE VENTAS 32.3

ARTICULO DE MAYOR VENTA EN EL ALMACEN

   COD DE ARTÍCULO  MONTO DE LA VENTA  VENTAS
9               38                400     108


### 7. Cargue una matriz A (8,8) de la siguiente manera:
#### • Llene con ceros (0) la diagonal principal.
#### • Llene con unos (1) la que quede encima de la diagonal principal.
#### • Llene con números (2) la que quede debajo de la diagonal principal.
#### • Imprima la matriz.


In [47]:
b = np.full((8,8), 2)
np.fill_diagonal(b, 0)

In [111]:
c = np.tril(b, 0)
np.fill_diagonal(c[:-1, 1:], 1)    
np.fill_diagonal(c[:-1, 2:], 1)
np.fill_diagonal(c[:-1, 3:], 1)
np.fill_diagonal(c[:-1, 4:], 1)
np.fill_diagonal(c[:-1, 5:], 1)
np.fill_diagonal(c[:-1, 6:], 1)
np.fill_diagonal(c[:-1, 7:], 1)

In [112]:
c

array([[0, 1, 1, 1, 1, 1, 1, 1],
       [2, 0, 1, 1, 1, 1, 1, 1],
       [2, 2, 0, 1, 1, 1, 1, 1],
       [2, 2, 2, 0, 1, 1, 1, 1],
       [2, 2, 2, 2, 0, 1, 1, 1],
       [2, 2, 2, 2, 2, 0, 1, 1],
       [2, 2, 2, 2, 2, 2, 0, 1],
       [2, 2, 2, 2, 2, 2, 2, 0]])